### ISSUE TITLE
[討論] 啟用 GitHub Issue Template

### ISSUE THREAD

**Issue by asika32764** [lyrasoft/development-tools#12]
一樣需要有人處理這件事
- See https://github.com/blog/2111-issue-and-pull-request-templates
- See also https://github.com/joomla/joomla-cms/tree/staging/.github

**Comment by kiyayeh** [comment]
不符合版規者罰掃廁所殺蟑螂以敬效尤

# Issue
1. 開 spec/feature 用
   ###主旨：
   ###時間：
   ###功能敘述：
2. [ ] 子功能
3. [ ] wireframe or 圖
4. [ ] 補充資料
5. [ ] 詳細敘述
6. 開 bug
   ###主旨：
   ###時間：
   ###重現步驟：
   ###預期結果：
   ###實際結果：
   ###System information (dev.php)
   ###補充

**Comment by asika32764** [comment]
要不要直接發個 PR 寫 issue template

**Comment by kiyayeh** [comment]
幹 怒 了

**Comment by asika32764** [comment]
2018 年重新規劃
