### ISSUE TITLE
修改 JS Code style 大括號換行規定

### ISSUE THREAD

**Issue by asika32764** [lyrasoft/development-tools#15]
目前我們的規定是 [Allman style](https://en.wikipedia.org/wiki/Indent_style#Allman_style)，也就是開頭大括號強制換一行

由於未來準備跟主流 Code style 整合，我們可以在年底的時候，預先把大括號換行這個最大的風格差異改過來 （但 php 還是先維持 Allman）

需要更改的部份是
- [ ] PHPStorm Code style 設定檔並匯出 https://github.com/lyrasoft/development-tools/blob/master/Editor/PHPStorm/CodeStyle.jar
- [ ] LYRASOFT JS Coding Standards 文件 https://github.com/lyrasoft/coding-standards/blob/master/javascript.md

完成後會發正式公告，則所有人「新寫」的程式碼必須符合規定

如果改到舊的程式碼，也必須至少將該檔案的 Style 轉成最新風格

**Comment by asika32764** [comment]
本工作請 @kiyayeh 監督 @EricTsao 完成

**Comment by kiyayeh** [comment]
@EricTsao  列入mic後接續工作

**Comment by EricTsao** [comment]
@asika32764 鳥哥, 跟你確認一下, PHPStorm的設定應該只要修改下圖紅筐的部分對嗎?
![preferences](https://cloud.githubusercontent.com/assets/2383506/20476307/3e4f9f7a-b00b-11e6-9d4a-591f97d25188.png)

**Comment by asika32764** [comment]
不確定，你可能要自己多測試看看

**Comment by EricTsao** [comment]
要修改的部分是, 所有大括弧開頭都要改為不換行, 對嗎?

**Comment by asika32764** [comment]
包含 else 或 catch 都在同一行

**Comment by EricTsao** [comment]
if條件式更改style後應該如下

``` javascript
if (foo == 'bar' && baz < 5) {
    // Code...
}
```

但如果條件式換行的話, 若大括號不換行, 看起來很不好閱讀, 這樣應該要怎麼訂?
``` javascript
if (a == b && c == d && e == f
    && g == h && j == k) {
    // Code...
}
```

**Comment by asika32764** [comment]
也沒辦法，若括號在同一行，則不管條件式有幾行都會維持原本格式

**Comment by EricTsao** [comment]
@asika32764 修改完PHPStorm的設定以後是要用save as來匯出嗎?

**Comment by asika32764** [comment]
![p-2016-11-21-001](https://cloud.githubusercontent.com/assets/1639206/20478621/d60ea2de-b015-11e6-959d-915e4230b1e7.jpg)
![p-2016-11-21-002](https://cloud.githubusercontent.com/assets/1639206/20478620/d60c9eb2-b015-11e6-80c1-234822244144.jpg)
