### ISSUE TITLE
[Draft] jQuery / Vue 編寫規範

### ISSUE THREAD

**Issue by asika32764** [lyrasoft/development-tools#18]
過去 jQuery 的編寫規範是經過長時間發展的，還沒有正式文件直接說明

目前 Vue 也還在發展穩定寫法，並且還需要與 jQuery 交互作用，未來必須要有正式的 Guide 規範所有人採用相同的模式編寫 JS 物件、命名、引入方式等等

先等 https://github.com/lyrasoft/development-tools/issues/15 完成後開始擬定草案，預計 2017 年中才能完成正式規範

**Comment by kiyayeh** [comment]
我jQuery之前這樣寫可以 但不確定2.0還能不能這樣

```
// @SECTION: third-party or app services
function Service() {
  // ...
}

// @SECTION: dependencies (singletons)
var service = new Service();
var dependencies = {
	init: function() {
  	this.$service = service;
  },
};

// @SECTION: app code
new Vue({
  el: '#demo',
  mixins: [ dependencies ],
  ready: function() {
  	console.log(this.$service);
  },
});
```

**Comment by asika32764** [comment]
我目前用的方法，但還是稍嫌繁雜
https://gist.github.com/asika32764/d4aa120446de6f1ccf6f572757d22632

**Comment by asika32764** [comment]
2018 年重新規劃
