### ISSUE TITLE
開案會議 Tamplate 2016/12/13開會後定稿，公告執行

### ISSUE THREAD

**Issue by adachang119** [lyrasoft/development-tools#20]
百岳國際會議記錄－開案會議議程討論

會議名稱：開案會議議程討論
日期：2016.12.13
主席：Stuart
記錄：Ada

出席人員：Stuart、Burce、Eric、Anny、Ada

會議開始時間：15:36

會議議程：

### 會議前準備：
1. 三天前文件備齊由召集人發出會議通知
2. 開啟google 專案案件資料夾
3. Slack channel，invite member，貼出會議通知以及相關文件
4. 專案語言框架
5. 第三方串接相關使用預先確定（server, smtp, 金流 , Oauth … 等）
6. 製作文件（需求清單、wireframe、sitemap、schema、mockup）
7. PM列重大議程（結案時程、內部驗收時程、前後台完成時程），先列在會議紀錄上

### 會議中討論事項：
1. 專案執行(詳細執行期程)  PM 帶簡報關於每頁細部功能（包含需求確認，user story，wireframe，設計稿），相關重要期程，確定每一個相關的milestone。
2. 與會人員發問提出相關問題。

### 會議後：
1. 開啟github專案，設立各個時程上的milestone 
2. 改用專案 README https://github.com/lyrasoft/development-tools/tree/master/Windwalker-Project
3. Google calendar標記milestone時間點
4. 把 Table Schema, Wireframe 等文件貼上 README (直連 Slack)
5. 設定 `preparedev` 等 script (參考 earth)
6. 放上模板檔案在 `/theme` 資料夾
7. 建立常用 Label (`PR Attached`, `Priority` 等等)
8. 建立檢討用會議記錄

### 名詞定義：

1. Wireframe：應加入設計，功能位置不應有太過大的變動（如不能由下變成左，但可以都在下方但靠右或置中等）
2. 第三方串接：包含物流、社群等等
3. 會議記錄：遇到問題時就先編輯到會議記錄

### 會議後執行事項：
1. 在 develop-tool 建立相關常用 Label 討論串
（Link:https://github.com/lyrasoft/development-tools/issues/21）

會議結束：4 :25

原始紀錄見：https://docs.google.com/document/d/13KDTNS960SdsSSbmBEHcrHh9riq0cS2QRv4Ri61czjc/edit#

**Comment by kiyayeh** [comment]
請貼上來

**Comment by adachang119** [comment]
已修正

**Comment by asika32764** [comment]
2018 年重新規劃
