### ISSUE TITLE
[公告] 以後用這邊作為開發技術討論區與 bug 集中回報區

### ISSUE THREAD

**Issue by asika32764** [lyrasoft/development-tools#3]
@kiyayeh @supergud @tedca886 

跟技術有關的內部工作我們集中在這邊討論吧，請大家把這個 repo 加入書籤

---
## Bug 統一回報

所有套件在這邊統一回報 bug 或新功能請求，我再各自整理到 repo 上面

標題統一用 `[套件名] 問題說明` ，例如 `[Ezset] Facebook Like 數量不正確`

內文標準請至少附上錯誤訊息或錯誤畫面截圖，如果可以的話稍微描述一下如何重現錯誤或者有沒有平台差異，我有修復時再 ref commit 或 PR 大家就知道已經修好了
## 流程討論

標題統一用 `[Discuss] 新專案建立流程討論` 這樣的格式

內文可提出自己的第一版建議，再交由大家用 Github 的投票機制討論
## 內部工作討論

同上，建立 issue 當作討論串，確認方向後再到專案管理平台開 task 工作
## 公告

`[公告]` 開頭的要求所有人閱讀後 +1
## README

可能要在 README 上面列一下我們的各個工作平台網址，方便大家從這裡做為入口平台開始各項作業

有沒有人要認領這項工作?
## 隱藏?

要把這個 repo 轉成 private 嗎?

**Comment by kiyayeh** [comment]
👍  @supergud @tedca886

**Comment by tedca886** [comment]
👍  了解！

**Comment by supergud** [comment]
:+1:

**Comment by asika32764** [comment]
@tedca886 這個工作麻煩妳處理可以嗎?

> 可能要在 README 上面列一下我們的各個工作平台網址，方便大家從這裡做為入口平台開始各項作業

發 PR 在 README.md 最上面
