### ISSUE TITLE
[WW] record 文件錯誤

### ISSUE THREAD

**Issue by kiyayeh** [lyrasoft/development-tools#4]
按照文件操作結果比預期的先爆掉。
Record 在 load 那一瞬間找不到就會先炸開。

![whoops__there_was_an_error__ _getcontroller_php_-_db-test_-___applications_xampp_xamppfiles_htdocs_www_project_db-test_](https://cloud.githubusercontent.com/assets/5356980/16186541/9f85e984-36fd-11e6-8b35-44bae3a46770.jpg)

**Comment by kiyayeh** [comment]
@asika32764

**Comment by kiyayeh** [comment]
![activerecord___windwalker_-_a_modern_php_framework](https://cloud.githubusercontent.com/assets/5356980/16186584/e67880b8-36fd-11e6-8c04-972927ab2b7c.jpg)

**Comment by asika32764** [comment]
是的，文件較舊

現在正確的做法改成要用 `try ... catch` 來包

``` php
try
{
   $record->load(25);
}
catch (NoResultException $e)
{
    // Do something to handle error.
}
```

不過這種情況可以閱讀一下錯誤訊息，訊息裡面其實可以看的出來怎麼處理。Windwalker 比較傾向用 Exception 來處理錯誤 (其實是 Record 已經把你寫的那個 Exception 做掉了)

文件原始檔在這邊
https://github.com/ventoviro/windwalker/blob/master/src/Record/README.md#load-a-record

https://github.com/ventoviro/ventoviro.github.io/blob/master/.vaseman/entries/documentation/db/active-record.md#load-a-record

有空可以直接幫忙改，從 Github 上按編輯就好了
