### ISSUE TITLE
專案開工會議 準備事項及內容 

### ISSUE THREAD

**Issue by kiyayeh** [lyrasoft/development-tools#7]
會議記錄：https://docs.google.com/document/d/1LvjC2GhfcHyleud0NV5z0a61d-pQh_cFT10JMjCoHTA/edit
### 會議前：
1. 三天前文件備齊由召集人發出會議通知
2. 開啟google 專案案件資料夾
3. Slack channel, invite member
4. 製作文件（wireframe, sitemap, schema）
5. Pm列重大議程，先列在會議紀錄上
### 會議中討論事項：
1. 專案使用工具及語言框架
2. 第三方串接相關使用預先確定
3. 專案執行(詳細執行期程)  PM 帶簡報關於每頁細部功能，相關重要期程
4. 與會人員發問提出相關問題
### 會議後：
1. 開啟github專案，設立各個時程上的milestone
2. Google calendar標記時間點

**Comment by asika32764** [comment]
Ref https://github.com/lyrasoft/ntu_mic/issues/4

**Comment by asika32764** [comment]
See https://github.com/lyrasoft/development-tools/issues/12

**Comment by asika32764** [comment]
每個 gitHub 專案需要處理的事項
- README
- Labels
- Issue & PR Templates

待補充...

**Comment by asika32764** [comment]
2018 年重新制定
